services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - "8080:8080"
        volumes:
            - type: bind
              source: ./server
              target: /app
              consistency: cached
            - /app/tmp
        env_file:
            - server/.env
        environment:
            - CGO_ENABLED=0
            - NODE_ENV=development
        stdin_open: true
        tty: true
        working_dir: /app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
