version: "3.8"

services:
    speecht5-tts:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./cache:/root/.cache/huggingface # Cache models
        environment:
            - TRANSFORMERS_CACHE=/root/.cache/huggingface
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
