[package]
name = "food_safety_contracts"
version = "1.0.0"
authors = []

[addresses]
food_safety_contracts = "0x0"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]